// DOM element handles for the expanded view. Resolved once at module load — safe
// because expanded.js loads with type="module" (deferred), so the DOM is parsed.

export const elements = {
  // Header
  openSettingsBtn: document.getElementById('openSettingsBtn') as HTMLButtonElement | null,
  refreshBtn: document.getElementById('refreshBtn')!,
  headerSubtitle: document.getElementById('headerSubtitle')!,
  settingsModal: document.getElementById('settingsModal'),
  closeSettingsBtn: document.getElementById('closeSettingsBtn') as HTMLButtonElement | null,
  saveSettingsBtn: document.getElementById('saveSettingsBtn') as HTMLButtonElement | null,
  resetSettingsBtn: document.getElementById('resetSettingsBtn') as HTMLButtonElement | null,
  themeMode: document.getElementById('themeMode') as HTMLSelectElement | null,
  rpcMainnet: document.getElementById('rpcMainnet') as HTMLInputElement | null,
  rpcTestnet: document.getElementById('rpcTestnet') as HTMLInputElement | null,
  explorerMainnet: document.getElementById('explorerMainnet') as HTMLInputElement | null,
  explorerTestnet: document.getElementById('explorerTestnet') as HTMLInputElement | null,
  lockTimeoutMinutes: document.getElementById('lockTimeoutMinutes') as HTMLInputElement | null,
  settingsFeedback: document.getElementById('settingsFeedback'),
  openChangePinBtn: document.getElementById('openChangePinBtn') as HTMLButtonElement | null,
  changePinModal: document.getElementById('changePinModal'),
  changePinCurrentView: document.getElementById('changePinCurrentView'),
  changePinNewView: document.getElementById('changePinNewView'),
  changePinCurrentInput: document.getElementById('changePinCurrentInput') as HTMLInputElement | null,
  changePinNewInput: document.getElementById('changePinNewInput') as HTMLInputElement | null,
  changePinConfirmInput: document.getElementById('changePinConfirmInput') as HTMLInputElement | null,
  changePinCurrentError: document.getElementById('changePinCurrentError'),
  changePinNewError: document.getElementById('changePinNewError'),
  cancelChangePinBtn: document.getElementById('cancelChangePinBtn') as HTMLButtonElement | null,
  verifyChangePinBtn: document.getElementById('verifyChangePinBtn') as HTMLButtonElement | null,
  backChangePinBtn: document.getElementById('backChangePinBtn') as HTMLButtonElement | null,
  saveChangePinBtn: document.getElementById('saveChangePinBtn') as HTMLButtonElement | null,
  openBackupBtn: document.getElementById('openBackupBtn') as HTMLButtonElement | null,
  removeWalletBtn: document.getElementById('removeWalletBtn') as HTMLButtonElement | null,
  backupModal: document.getElementById('backupModal'),
  closeBackupBtn: document.getElementById('closeBackupBtn') as HTMLButtonElement | null,
  backupAuthSection: document.getElementById('backupAuthSection'),
  backupDataSection: document.getElementById('backupDataSection'),
  backupPinInput: document.getElementById('backupPinInput') as HTMLInputElement | null,
  backupError: document.getElementById('backupError'),
  backupUnlockBtn: document.getElementById('backupUnlockBtn') as HTMLButtonElement | null,
  backupMnemonicGroup: document.getElementById('backupMnemonicGroup'),
  backupMnemonicWords: document.getElementById('backupMnemonicWords'),
  backupCopyMnemonicBtn: document.getElementById('backupCopyMnemonicBtn') as HTMLButtonElement | null,
  backupPassphraseGroup: document.getElementById('backupPassphraseGroup'),
  backupPassphraseText: document.getElementById('backupPassphraseText'),
  backupWifText: document.getElementById('backupWifText') as HTMLInputElement | null,
  toggleBackupWifBtn: document.getElementById('toggleBackupWifBtn') as HTMLButtonElement | null,
  backupCopyWifBtn: document.getElementById('backupCopyWifBtn') as HTMLButtonElement | null,
  removeConfirmModal: document.getElementById('removeConfirmModal'),
  removeConfirmText: document.getElementById('removeConfirmText'),
  cancelRemoveBtn: document.getElementById('cancelRemoveBtn') as HTMLButtonElement | null,
  confirmRemoveBtn: document.getElementById('confirmRemoveBtn') as HTMLButtonElement | null,

  // Sections
  setupSection: document.getElementById('setupSection'),
  mnemonicSection: document.getElementById('mnemonicSection')!,
  walletSection: document.getElementById('walletSection')!,

  // Wallet display
  copyAddressBtn: document.getElementById('copyAddressBtn')!,
  changeAccountBtn: document.getElementById('changeAccountBtn') as HTMLButtonElement | null,
  newAccountBtn: document.getElementById('newAccountBtn') as HTMLButtonElement | null,
  networkValue: document.getElementById('networkValue')!,
  accountValue: document.getElementById('accountValue')!,
  statusValue: document.getElementById('statusValue')!,
  addressValue: document.getElementById('addressValue')!,
  balanceValue: document.getElementById('balanceValue')!,
  pendingValue: document.getElementById('pendingValue')!,
  balancePanelAssets: document.getElementById('balancePanelAssets'),
  assetsList: document.getElementById('assetsList')!,
  assetsEmpty: document.getElementById('assetsEmpty')!,
  assetsPager: document.getElementById('assetsPager'),
  assetsPrevBtn: document.getElementById('assetsPrevBtn') as HTMLButtonElement | null,
  assetsNextBtn: document.getElementById('assetsNextBtn') as HTMLButtonElement | null,
  assetsPageLabel: document.getElementById('assetsPageLabel'),
  assetsFilterBar: document.getElementById('assetsFilterBar'),
  historyList: document.getElementById('historyList')!,
  historyEmpty: document.getElementById('historyEmpty')!,
  unlockModal: document.getElementById('unlockModal')!,
  unlockPinInput: document.getElementById('unlockPinInput') as HTMLInputElement,
  unlockError: document.getElementById('unlockError')!,
  unlockConfirmBtn: document.getElementById('unlockConfirmBtn')!,
  unlockPrimaryView: document.getElementById('unlockPrimaryView')!,
  unlockForgotPinLink: document.getElementById('unlockForgotPinLink')!,
  unlockResetView: document.getElementById('unlockResetView')!,
  unlockResetInput: document.getElementById('unlockResetInput') as HTMLInputElement,
  unlockResetMessage: document.getElementById('unlockResetMessage')!,
  unlockResetCancelBtn: document.getElementById('unlockResetCancelBtn')!,
  unlockResetConfirmBtn: document.getElementById('unlockResetConfirmBtn')!,

  hardwareCard: document.getElementById('hardwareCard'),
  hwStatusDot: document.getElementById('hwStatusDot'),
  hwStatusText: document.getElementById('hwStatusText'),
  hwReconnectBtn: document.getElementById('hwReconnectBtn') as HTMLButtonElement | null,
  recentMovementsList: document.getElementById('recentMovementsList')!,
  recentMovementsEmpty: document.getElementById('recentMovementsEmpty')!,
  recentMovementsPager: document.getElementById('recentMovementsPager'),
  recentMovementsPrevBtn: document.getElementById('recentMovementsPrevBtn') as HTMLButtonElement | null,
  recentMovementsNextBtn: document.getElementById('recentMovementsNextBtn') as HTMLButtonElement | null,
  recentMovementsPageLabel: document.getElementById('recentMovementsPageLabel'),
  historyPager: document.getElementById('historyPager'),
  historyPrevBtn: document.getElementById('historyPrevBtn') as HTMLButtonElement | null,
  historyNextBtn: document.getElementById('historyNextBtn') as HTMLButtonElement | null,
  historyPageLabel: document.getElementById('historyPageLabel'),
  createAssetCard: document.getElementById('createAssetCard'),
  assetTypeTabs: document.getElementById('assetTypeTabs'),
  caAssetNameGroup: document.getElementById('caAssetNameGroup'),
  caAssetName: document.getElementById('caAssetName') as HTMLInputElement | null,
  caAssetNameHint: document.getElementById('caAssetNameHint'),
  caParentSelectGroup: document.getElementById('caParentSelectGroup'),
  caParentSelectLabel: document.getElementById('caParentSelectLabel'),
  caParentSelect: document.getElementById('caParentSelect') as HTMLSelectElement | null,
  caLoadParentsBtn: document.getElementById('caLoadParentsBtn') as HTMLButtonElement | null,
  caParentSelectHint: document.getElementById('caParentSelectHint'),
  caRestrictedBaseGroup: document.getElementById('caRestrictedBaseGroup'),
  caRestrictedBaseSelect: document.getElementById('caRestrictedBaseSelect') as HTMLSelectElement | null,
  caLoadRestrictedBasesBtn: document.getElementById('caLoadRestrictedBasesBtn') as HTMLButtonElement | null,
  caRestrictedBaseHint: document.getElementById('caRestrictedBaseHint'),
  caSubNameGroup: document.getElementById('caSubNameGroup'),
  caSubName: document.getElementById('caSubName') as HTMLInputElement | null,
  caTagGroup: document.getElementById('caTagGroup'),
  caTag: document.getElementById('caTag') as HTMLInputElement | null,
  caQuantityGroup: document.getElementById('caQuantityGroup'),
  caQuantityLabel: document.getElementById('caQuantityLabel'),
  caQuantity: document.getElementById('caQuantity') as HTMLInputElement | null,
  caUnitsGroup: document.getElementById('caUnitsGroup'),
  caUnits: document.getElementById('caUnits') as HTMLSelectElement | null,
  caReissuableGroup: document.getElementById('caReissuableGroup'),
  caReissuable: document.getElementById('caReissuable') as HTMLInputElement | null,
  caReissuableLabel: document.getElementById('caReissuableLabel'),
  caVerifierGroup: document.getElementById('caVerifierGroup'),
  caVerifier: document.getElementById('caVerifier') as HTMLInputElement | null,
  caVerifierSelect: document.getElementById('caVerifierSelect') as HTMLSelectElement | null,
  caLoadVerifiersBtn: document.getElementById('caLoadVerifiersBtn') as HTMLButtonElement | null,
  caVerifierAddBtn: document.getElementById('caVerifierAddBtn') as HTMLButtonElement | null,
  caVerifierNegateBtn: document.getElementById('caVerifierNegateBtn') as HTMLButtonElement | null,
  caVerifierAndBtn: document.getElementById('caVerifierAndBtn') as HTMLButtonElement | null,
  caVerifierOrBtn: document.getElementById('caVerifierOrBtn') as HTMLButtonElement | null,
  caVerifierClearBtn: document.getElementById('caVerifierClearBtn') as HTMLButtonElement | null,
  caVerifierPreview: document.getElementById('caVerifierPreview'),
  caVerifierHint: document.getElementById('caVerifierHint'),
  caIpfsHash: document.getElementById('caIpfsHash') as HTMLInputElement | null,
  caFeeValue: document.getElementById('caFeeValue'),
  caError: document.getElementById('caError'),
  caCreateBtn: document.getElementById('caCreateBtn') as HTMLButtonElement | null,
  caResult: document.getElementById('caResult'),
  caTxid: document.getElementById('caTxid'),
  caNewBtn: document.getElementById('caNewBtn') as HTMLButtonElement | null,
  caTxConfirmModal: document.getElementById('caTxConfirmModal'),
  caTxOutputsList: document.getElementById('caTxOutputsList'),
  caTxRawToggle: document.getElementById('caTxRawToggle') as HTMLButtonElement | null,
  caTxRawHex: document.getElementById('caTxRawHex'),
  caTxDebugToggle: document.getElementById('caTxDebugToggle') as HTMLButtonElement | null,
  caTxDebugJson: document.getElementById('caTxDebugJson'),
  caTxConfirmError: document.getElementById('caTxConfirmError'),
  caTxCancelBtn: document.getElementById('caTxCancelBtn') as HTMLButtonElement | null,
  caTxBroadcastBtn: document.getElementById('caTxBroadcastBtn') as HTMLButtonElement | null,
  // Card mode toggle
  assetModeToggle: document.getElementById('assetModeToggle'),
  caCardTitle: document.getElementById('caCardTitle'),
  caCardCopy: document.getElementById('caCardCopy'),
  createAssetPanel: document.getElementById('createAssetPanel'),
  configureAssetPanel: document.getElementById('configureAssetPanel'),
  // Configure panel
  cfTypeTabs: document.getElementById('cfTypeTabs'),
  cfOwnerTokenGroup: document.getElementById('cfOwnerTokenGroup'),
  cfOwnerTokenLabel: document.getElementById('cfOwnerTokenLabel'),
  cfOwnerTokenSelect: document.getElementById('cfOwnerTokenSelect') as HTMLSelectElement | null,
  cfOwnerTokenHint: document.getElementById('cfOwnerTokenHint'),
  cfLoadTokensBtn: document.getElementById('cfLoadTokensBtn') as HTMLButtonElement | null,
  cfAddressesGroup: document.getElementById('cfAddressesGroup'),
  cfAddresses: document.getElementById('cfAddresses') as HTMLTextAreaElement | null,
  cfGlobalGroup: document.getElementById('cfGlobalGroup'),
  cfGlobal: document.getElementById('cfGlobal') as HTMLInputElement | null,
  cfQuantityGroup: document.getElementById('cfQuantityGroup'),
  cfQuantity: document.getElementById('cfQuantity') as HTMLInputElement | null,
  cfChangeVerifierGroup: document.getElementById('cfChangeVerifierGroup'),
  cfChangeVerifier: document.getElementById('cfChangeVerifier') as HTMLInputElement | null,
  cfNewVerifierGroup: document.getElementById('cfNewVerifierGroup'),
  cfNewVerifier: document.getElementById('cfNewVerifier') as HTMLInputElement | null,
  cfReissuableGroup: document.getElementById('cfReissuableGroup'),
  cfReissuable: document.getElementById('cfReissuable') as HTMLInputElement | null,
  cfNewIpfsGroup: document.getElementById('cfNewIpfsGroup'),
  cfNewIpfs: document.getElementById('cfNewIpfs') as HTMLInputElement | null,
  cfFeeRow: document.getElementById('cfFeeRow'),
  cfFeeValue: document.getElementById('cfFeeValue'),
  cfError: document.getElementById('cfError'),
  cfApplyBtn: document.getElementById('cfApplyBtn') as HTMLButtonElement | null,
};
